//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGastosWS.ExpenseAccountServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UltExpenseFlowVariables", Namespace="http://schemas.datacontract.org/2004/07/Entities.Ultimus")]
    [System.SerializableAttribute()]
    public partial class UltExpenseFlowVariables : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeDirAreaGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeDirFinanzasGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeDirGralGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionAutorizador1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionAutorizador2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionAutorizador3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionAutorizador4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionController1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionController2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionControllingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionDirAreaGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionFinanzasGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionNationalManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionObservadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionResponsibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string summaryTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activeDirAreaGastos {
            get {
                return this.activeDirAreaGastosField;
            }
            set {
                if ((this.activeDirAreaGastosField.Equals(value) != true)) {
                    this.activeDirAreaGastosField = value;
                    this.RaisePropertyChanged("activeDirAreaGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activeDirFinanzasGastos {
            get {
                return this.activeDirFinanzasGastosField;
            }
            set {
                if ((this.activeDirFinanzasGastosField.Equals(value) != true)) {
                    this.activeDirFinanzasGastosField = value;
                    this.RaisePropertyChanged("activeDirFinanzasGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activeDirGralGastos {
            get {
                return this.activeDirGralGastosField;
            }
            set {
                if ((this.activeDirGralGastosField.Equals(value) != true)) {
                    this.activeDirGralGastosField = value;
                    this.RaisePropertyChanged("activeDirGralGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activeManager {
            get {
                return this.activeManagerField;
            }
            set {
                if ((this.activeManagerField.Equals(value) != true)) {
                    this.activeManagerField = value;
                    this.RaisePropertyChanged("activeManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionAutorizador1 {
            get {
                return this.jobFunctionAutorizador1Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionAutorizador1Field, value) != true)) {
                    this.jobFunctionAutorizador1Field = value;
                    this.RaisePropertyChanged("jobFunctionAutorizador1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionAutorizador2 {
            get {
                return this.jobFunctionAutorizador2Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionAutorizador2Field, value) != true)) {
                    this.jobFunctionAutorizador2Field = value;
                    this.RaisePropertyChanged("jobFunctionAutorizador2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionAutorizador3 {
            get {
                return this.jobFunctionAutorizador3Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionAutorizador3Field, value) != true)) {
                    this.jobFunctionAutorizador3Field = value;
                    this.RaisePropertyChanged("jobFunctionAutorizador3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionAutorizador4 {
            get {
                return this.jobFunctionAutorizador4Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionAutorizador4Field, value) != true)) {
                    this.jobFunctionAutorizador4Field = value;
                    this.RaisePropertyChanged("jobFunctionAutorizador4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionController1 {
            get {
                return this.jobFunctionController1Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionController1Field, value) != true)) {
                    this.jobFunctionController1Field = value;
                    this.RaisePropertyChanged("jobFunctionController1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionController2 {
            get {
                return this.jobFunctionController2Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionController2Field, value) != true)) {
                    this.jobFunctionController2Field = value;
                    this.RaisePropertyChanged("jobFunctionController2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionControlling {
            get {
                return this.jobFunctionControllingField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionControllingField, value) != true)) {
                    this.jobFunctionControllingField = value;
                    this.RaisePropertyChanged("jobFunctionControlling");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionDirAreaGastos {
            get {
                return this.jobFunctionDirAreaGastosField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionDirAreaGastosField, value) != true)) {
                    this.jobFunctionDirAreaGastosField = value;
                    this.RaisePropertyChanged("jobFunctionDirAreaGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionFinanzasGastos {
            get {
                return this.jobFunctionFinanzasGastosField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionFinanzasGastosField, value) != true)) {
                    this.jobFunctionFinanzasGastosField = value;
                    this.RaisePropertyChanged("jobFunctionFinanzasGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionNationalManager {
            get {
                return this.jobFunctionNationalManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionNationalManagerField, value) != true)) {
                    this.jobFunctionNationalManagerField = value;
                    this.RaisePropertyChanged("jobFunctionNationalManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionObservador {
            get {
                return this.jobFunctionObservadorField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionObservadorField, value) != true)) {
                    this.jobFunctionObservadorField = value;
                    this.RaisePropertyChanged("jobFunctionObservador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionResponsible {
            get {
                return this.jobFunctionResponsibleField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionResponsibleField, value) != true)) {
                    this.jobFunctionResponsibleField = value;
                    this.RaisePropertyChanged("jobFunctionResponsible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string summaryText {
            get {
                return this.summaryTextField;
            }
            set {
                if ((object.ReferenceEquals(this.summaryTextField, value) != true)) {
                    this.summaryTextField = value;
                    this.RaisePropertyChanged("summaryText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UltRequest", Namespace="http://schemas.datacontract.org/2004/07/Entities.Ultimus")]
    [System.SerializableAttribute()]
    public partial class UltRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CeCoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CeCoMiniCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CeCoMiniNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CeCoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PEPElementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PEPElementNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int areaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string areaTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string arrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int companyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double exchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string initiatorLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string initiatorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isMiniEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool pasteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime requestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsibleEmployeeNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsibleLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsibleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsiblePayMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsibleUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> salesForceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ultimusNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CeCoCode {
            get {
                return this.CeCoCodeField;
            }
            set {
                if ((this.CeCoCodeField.Equals(value) != true)) {
                    this.CeCoCodeField = value;
                    this.RaisePropertyChanged("CeCoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CeCoMiniCode {
            get {
                return this.CeCoMiniCodeField;
            }
            set {
                if ((this.CeCoMiniCodeField.Equals(value) != true)) {
                    this.CeCoMiniCodeField = value;
                    this.RaisePropertyChanged("CeCoMiniCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CeCoMiniName {
            get {
                return this.CeCoMiniNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CeCoMiniNameField, value) != true)) {
                    this.CeCoMiniNameField = value;
                    this.RaisePropertyChanged("CeCoMiniName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CeCoName {
            get {
                return this.CeCoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CeCoNameField, value) != true)) {
                    this.CeCoNameField = value;
                    this.RaisePropertyChanged("CeCoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAClientId {
            get {
                return this.PAClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PAClientIdField, value) != true)) {
                    this.PAClientIdField = value;
                    this.RaisePropertyChanged("PAClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAClientName {
            get {
                return this.PAClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PAClientNameField, value) != true)) {
                    this.PAClientNameField = value;
                    this.RaisePropertyChanged("PAClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PEPElementId {
            get {
                return this.PEPElementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PEPElementIdField, value) != true)) {
                    this.PEPElementIdField = value;
                    this.RaisePropertyChanged("PEPElementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PEPElementName {
            get {
                return this.PEPElementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PEPElementNameField, value) != true)) {
                    this.PEPElementNameField = value;
                    this.RaisePropertyChanged("PEPElementName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int areaId {
            get {
                return this.areaIdField;
            }
            set {
                if ((this.areaIdField.Equals(value) != true)) {
                    this.areaIdField = value;
                    this.RaisePropertyChanged("areaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string areaText {
            get {
                return this.areaTextField;
            }
            set {
                if ((object.ReferenceEquals(this.areaTextField, value) != true)) {
                    this.areaTextField = value;
                    this.RaisePropertyChanged("areaText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string arrival {
            get {
                return this.arrivalField;
            }
            set {
                if ((object.ReferenceEquals(this.arrivalField, value) != true)) {
                    this.arrivalField = value;
                    this.RaisePropertyChanged("arrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int companyCode {
            get {
                return this.companyCodeField;
            }
            set {
                if ((this.companyCodeField.Equals(value) != true)) {
                    this.companyCodeField = value;
                    this.RaisePropertyChanged("companyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currencyId {
            get {
                return this.currencyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyIdField, value) != true)) {
                    this.currencyIdField = value;
                    this.RaisePropertyChanged("currencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currencyName {
            get {
                return this.currencyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyNameField, value) != true)) {
                    this.currencyNameField = value;
                    this.RaisePropertyChanged("currencyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureDate {
            get {
                return this.departureDateField;
            }
            set {
                if ((object.ReferenceEquals(this.departureDateField, value) != true)) {
                    this.departureDateField = value;
                    this.RaisePropertyChanged("departureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double exchangeRate {
            get {
                return this.exchangeRateField;
            }
            set {
                if ((this.exchangeRateField.Equals(value) != true)) {
                    this.exchangeRateField = value;
                    this.RaisePropertyChanged("exchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRequest {
            get {
                return this.idRequestField;
            }
            set {
                if ((this.idRequestField.Equals(value) != true)) {
                    this.idRequestField = value;
                    this.RaisePropertyChanged("idRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string initiatorLogin {
            get {
                return this.initiatorLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.initiatorLoginField, value) != true)) {
                    this.initiatorLoginField = value;
                    this.RaisePropertyChanged("initiatorLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string initiatorName {
            get {
                return this.initiatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.initiatorNameField, value) != true)) {
                    this.initiatorNameField = value;
                    this.RaisePropertyChanged("initiatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isMiniEvent {
            get {
                return this.isMiniEventField;
            }
            set {
                if ((this.isMiniEventField.Equals(value) != true)) {
                    this.isMiniEventField = value;
                    this.RaisePropertyChanged("isMiniEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool pasteur {
            get {
                return this.pasteurField;
            }
            set {
                if ((this.pasteurField.Equals(value) != true)) {
                    this.pasteurField = value;
                    this.RaisePropertyChanged("pasteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                if ((this.requestDateField.Equals(value) != true)) {
                    this.requestDateField = value;
                    this.RaisePropertyChanged("requestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsibleEmployeeNum {
            get {
                return this.responsibleEmployeeNumField;
            }
            set {
                if ((object.ReferenceEquals(this.responsibleEmployeeNumField, value) != true)) {
                    this.responsibleEmployeeNumField = value;
                    this.RaisePropertyChanged("responsibleEmployeeNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsibleLogin {
            get {
                return this.responsibleLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.responsibleLoginField, value) != true)) {
                    this.responsibleLoginField = value;
                    this.RaisePropertyChanged("responsibleLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsibleName {
            get {
                return this.responsibleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.responsibleNameField, value) != true)) {
                    this.responsibleNameField = value;
                    this.RaisePropertyChanged("responsibleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsiblePayMethod {
            get {
                return this.responsiblePayMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.responsiblePayMethodField, value) != true)) {
                    this.responsiblePayMethodField = value;
                    this.RaisePropertyChanged("responsiblePayMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsibleUserName {
            get {
                return this.responsibleUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.responsibleUserNameField, value) != true)) {
                    this.responsibleUserNameField = value;
                    this.RaisePropertyChanged("responsibleUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string returnDate {
            get {
                return this.returnDateField;
            }
            set {
                if ((object.ReferenceEquals(this.returnDateField, value) != true)) {
                    this.returnDateField = value;
                    this.RaisePropertyChanged("returnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> salesForce {
            get {
                return this.salesForceField;
            }
            set {
                if ((this.salesForceField.Equals(value) != true)) {
                    this.salesForceField = value;
                    this.RaisePropertyChanged("salesForce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statusName {
            get {
                return this.statusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.statusNameField, value) != true)) {
                    this.statusNameField = value;
                    this.RaisePropertyChanged("statusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeName {
            get {
                return this.typeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.typeNameField, value) != true)) {
                    this.typeNameField = value;
                    this.RaisePropertyChanged("typeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ultimusNumber {
            get {
                return this.ultimusNumberField;
            }
            set {
                if ((this.ultimusNumberField.Equals(value) != true)) {
                    this.ultimusNumberField = value;
                    this.RaisePropertyChanged("ultimusNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UltExpenseAccount", Namespace="http://schemas.datacontract.org/2004/07/Entities.Ultimus")]
    [System.SerializableAttribute()]
    public partial class UltExpenseAccount : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool chargedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool debitCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idExpenseAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isCFDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nationalManagerLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nationalManagerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool overdueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool strikeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalMealField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalMiniEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalNationalMealField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool charged {
            get {
                return this.chargedField;
            }
            set {
                if ((this.chargedField.Equals(value) != true)) {
                    this.chargedField = value;
                    this.RaisePropertyChanged("charged");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool debitCard {
            get {
                return this.debitCardField;
            }
            set {
                if ((this.debitCardField.Equals(value) != true)) {
                    this.debitCardField = value;
                    this.RaisePropertyChanged("debitCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idExpenseAccount {
            get {
                return this.idExpenseAccountField;
            }
            set {
                if ((this.idExpenseAccountField.Equals(value) != true)) {
                    this.idExpenseAccountField = value;
                    this.RaisePropertyChanged("idExpenseAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRequest {
            get {
                return this.idRequestField;
            }
            set {
                if ((this.idRequestField.Equals(value) != true)) {
                    this.idRequestField = value;
                    this.RaisePropertyChanged("idRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isCFDI {
            get {
                return this.isCFDIField;
            }
            set {
                if ((this.isCFDIField.Equals(value) != true)) {
                    this.isCFDIField = value;
                    this.RaisePropertyChanged("isCFDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nationalManagerLogin {
            get {
                return this.nationalManagerLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.nationalManagerLoginField, value) != true)) {
                    this.nationalManagerLoginField = value;
                    this.RaisePropertyChanged("nationalManagerLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nationalManagerName {
            get {
                return this.nationalManagerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.nationalManagerNameField, value) != true)) {
                    this.nationalManagerNameField = value;
                    this.RaisePropertyChanged("nationalManagerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool overdue {
            get {
                return this.overdueField;
            }
            set {
                if ((this.overdueField.Equals(value) != true)) {
                    this.overdueField = value;
                    this.RaisePropertyChanged("overdue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool strike {
            get {
                return this.strikeField;
            }
            set {
                if ((this.strikeField.Equals(value) != true)) {
                    this.strikeField = value;
                    this.RaisePropertyChanged("strike");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double totalMeal {
            get {
                return this.totalMealField;
            }
            set {
                if ((this.totalMealField.Equals(value) != true)) {
                    this.totalMealField = value;
                    this.RaisePropertyChanged("totalMeal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double totalMiniEvent {
            get {
                return this.totalMiniEventField;
            }
            set {
                if ((this.totalMiniEventField.Equals(value) != true)) {
                    this.totalMiniEventField = value;
                    this.RaisePropertyChanged("totalMiniEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double totalNationalMeal {
            get {
                return this.totalNationalMealField;
            }
            set {
                if ((this.totalNationalMealField.Equals(value) != true)) {
                    this.totalNationalMealField = value;
                    this.RaisePropertyChanged("totalNationalMeal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UltExpenseAccountDetail", Namespace="http://schemas.datacontract.org/2004/07/Entities.Ultimus")]
    [System.SerializableAttribute()]
    public partial class UltExpenseAccountDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double IVAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IVATypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IVATypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double amountCFDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double amountExtractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool conciliatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double discountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime expenseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool hasPAClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool healthProfessionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> idExpenseAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idExpenseAccountDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idExtractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string invoiceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ivaCFDIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int numberOfDinersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int observationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string placeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool strikeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double IVA {
            get {
                return this.IVAField;
            }
            set {
                if ((this.IVAField.Equals(value) != true)) {
                    this.IVAField = value;
                    this.RaisePropertyChanged("IVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IVATypeId {
            get {
                return this.IVATypeIdField;
            }
            set {
                if ((object.ReferenceEquals(this.IVATypeIdField, value) != true)) {
                    this.IVATypeIdField = value;
                    this.RaisePropertyChanged("IVATypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IVATypeName {
            get {
                return this.IVATypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.IVATypeNameField, value) != true)) {
                    this.IVATypeNameField = value;
                    this.RaisePropertyChanged("IVATypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string accountName {
            get {
                return this.accountNameField;
            }
            set {
                if ((object.ReferenceEquals(this.accountNameField, value) != true)) {
                    this.accountNameField = value;
                    this.RaisePropertyChanged("accountName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double amount {
            get {
                return this.amountField;
            }
            set {
                if ((this.amountField.Equals(value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double amountCFDI {
            get {
                return this.amountCFDIField;
            }
            set {
                if ((this.amountCFDIField.Equals(value) != true)) {
                    this.amountCFDIField = value;
                    this.RaisePropertyChanged("amountCFDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double amountExtract {
            get {
                return this.amountExtractField;
            }
            set {
                if ((this.amountExtractField.Equals(value) != true)) {
                    this.amountExtractField = value;
                    this.RaisePropertyChanged("amountExtract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool conciliated {
            get {
                return this.conciliatedField;
            }
            set {
                if ((this.conciliatedField.Equals(value) != true)) {
                    this.conciliatedField = value;
                    this.RaisePropertyChanged("conciliated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double discount {
            get {
                return this.discountField;
            }
            set {
                if ((this.discountField.Equals(value) != true)) {
                    this.discountField = value;
                    this.RaisePropertyChanged("discount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime expenseDate {
            get {
                return this.expenseDateField;
            }
            set {
                if ((this.expenseDateField.Equals(value) != true)) {
                    this.expenseDateField = value;
                    this.RaisePropertyChanged("expenseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool hasPAClient {
            get {
                return this.hasPAClientField;
            }
            set {
                if ((this.hasPAClientField.Equals(value) != true)) {
                    this.hasPAClientField = value;
                    this.RaisePropertyChanged("hasPAClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool healthProfessional {
            get {
                return this.healthProfessionalField;
            }
            set {
                if ((this.healthProfessionalField.Equals(value) != true)) {
                    this.healthProfessionalField = value;
                    this.RaisePropertyChanged("healthProfessional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idAccount {
            get {
                return this.idAccountField;
            }
            set {
                if ((this.idAccountField.Equals(value) != true)) {
                    this.idAccountField = value;
                    this.RaisePropertyChanged("idAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> idExpenseAccount {
            get {
                return this.idExpenseAccountField;
            }
            set {
                if ((this.idExpenseAccountField.Equals(value) != true)) {
                    this.idExpenseAccountField = value;
                    this.RaisePropertyChanged("idExpenseAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExpenseAccountDetail {
            get {
                return this.idExpenseAccountDetailField;
            }
            set {
                if ((this.idExpenseAccountDetailField.Equals(value) != true)) {
                    this.idExpenseAccountDetailField = value;
                    this.RaisePropertyChanged("idExpenseAccountDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExtract {
            get {
                return this.idExtractField;
            }
            set {
                if ((this.idExtractField.Equals(value) != true)) {
                    this.idExtractField = value;
                    this.RaisePropertyChanged("idExtract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idXml {
            get {
                return this.idXmlField;
            }
            set {
                if ((this.idXmlField.Equals(value) != true)) {
                    this.idXmlField = value;
                    this.RaisePropertyChanged("idXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string invoiceNumber {
            get {
                return this.invoiceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.invoiceNumberField, value) != true)) {
                    this.invoiceNumberField = value;
                    this.RaisePropertyChanged("invoiceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double ivaCFDI {
            get {
                return this.ivaCFDIField;
            }
            set {
                if ((this.ivaCFDIField.Equals(value) != true)) {
                    this.ivaCFDIField = value;
                    this.RaisePropertyChanged("ivaCFDI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int numberOfDiners {
            get {
                return this.numberOfDinersField;
            }
            set {
                if ((this.numberOfDinersField.Equals(value) != true)) {
                    this.numberOfDinersField = value;
                    this.RaisePropertyChanged("numberOfDiners");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int observationId {
            get {
                return this.observationIdField;
            }
            set {
                if ((this.observationIdField.Equals(value) != true)) {
                    this.observationIdField = value;
                    this.RaisePropertyChanged("observationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observationName {
            get {
                return this.observationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.observationNameField, value) != true)) {
                    this.observationNameField = value;
                    this.RaisePropertyChanged("observationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string place {
            get {
                return this.placeField;
            }
            set {
                if ((object.ReferenceEquals(this.placeField, value) != true)) {
                    this.placeField = value;
                    this.RaisePropertyChanged("place");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool strike {
            get {
                return this.strikeField;
            }
            set {
                if ((this.strikeField.Equals(value) != true)) {
                    this.strikeField = value;
                    this.RaisePropertyChanged("strike");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UltPAClient", Namespace="http://schemas.datacontract.org/2004/07/Entities.Ultimus")]
    [System.SerializableAttribute()]
    public partial class UltPAClient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idExpenseAccountDetailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idExpenseAccountDetail {
            get {
                return this.idExpenseAccountDetailField;
            }
            set {
                if ((this.idExpenseAccountDetailField.Equals(value) != true)) {
                    this.idExpenseAccountDetailField = value;
                    this.RaisePropertyChanged("idExpenseAccountDetail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExpenseAccountServiceReference.IExpenseAccount")]
    public interface IExpenseAccount {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/initiateVariables", ReplyAction="http://tempuri.org/IExpenseAccount/initiateVariablesResponse")]
        void initiateVariables(
                    System.DateTime requestDate, 
                    string companyName, 
                    int companyCode, 
                    int CeCoCode, 
                    int CeCoMiniCode, 
                    string CeCoMiniName, 
                    bool isMiniEvent, 
                    string arrival, 
                    string departureDate, 
                    string returnDate, 
                    string PEPElementId, 
                    string PEPElementName, 
                    string currencyId, 
                    string currencyName, 
                    string initiatorLogin, 
                    string initiatorName, 
                    string responsibleLogin, 
                    string responsibleName, 
                    string responsibleEmployeeNum, 
                    string responsibleUserName, 
                    bool pasteur, 
                    int areaId, 
                    string areaText, 
                    bool salesForce, 
                    string nationalManagerLogin, 
                    string nationalManagerName, 
                    bool debitCard, 
                    bool strike, 
                    bool isCFDI);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/createExpenseAccountDetail", ReplyAction="http://tempuri.org/IExpenseAccount/createExpenseAccountDetailResponse")]
        void createExpenseAccountDetail(
                    int idExpenseAccountDetail, 
                    System.DateTime expenseDate, 
                    int idAccount, 
                    string accountName, 
                    double amount, 
                    string invoiceNumber, 
                    string place, 
                    int numberOfDiners, 
                    double IVA, 
                    bool healthProfessional, 
                    bool hasPAClient, 
                    double total, 
                    int observationId, 
                    string observationName, 
                    int idXml, 
                    double amountCFDI, 
                    double ivaCFDI, 
                    int idExtract, 
                    double amountExtract, 
                    bool conciliated, 
                    bool strike);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/createPAClient", ReplyAction="http://tempuri.org/IExpenseAccount/createPAClientResponse")]
        void createPAClient(int idExpenseAccountDetail, string code, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/createResponsible", ReplyAction="http://tempuri.org/IExpenseAccount/createResponsibleResponse")]
        void createResponsible(string responsibleMail, double gasLimit);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/validateAndSaveRequest", ReplyAction="http://tempuri.org/IExpenseAccount/validateAndSaveRequestResponse")]
        string validateAndSaveRequest(int attachCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/updateRequest", ReplyAction="http://tempuri.org/IExpenseAccount/updateRequestResponse")]
        bool updateRequest(int ultimusNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/getUltExpenseFlowVariables", ReplyAction="http://tempuri.org/IExpenseAccount/getUltExpenseFlowVariablesResponse")]
        eGastosWS.ExpenseAccountServiceReference.UltExpenseFlowVariables getUltExpenseFlowVariables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/getUltRequest", ReplyAction="http://tempuri.org/IExpenseAccount/getUltRequestResponse")]
        eGastosWS.ExpenseAccountServiceReference.UltRequest getUltRequest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/getUltExpenseAccount", ReplyAction="http://tempuri.org/IExpenseAccount/getUltExpenseAccountResponse")]
        eGastosWS.ExpenseAccountServiceReference.UltExpenseAccount getUltExpenseAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/getUltExpenseAccountDetailList", ReplyAction="http://tempuri.org/IExpenseAccount/getUltExpenseAccountDetailListResponse")]
        eGastosWS.ExpenseAccountServiceReference.UltExpenseAccountDetail[] getUltExpenseAccountDetailList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExpenseAccount/getUltPAClientList", ReplyAction="http://tempuri.org/IExpenseAccount/getUltPAClientListResponse")]
        eGastosWS.ExpenseAccountServiceReference.UltPAClient[] getUltPAClientList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IExpenseAccountChannel : eGastosWS.ExpenseAccountServiceReference.IExpenseAccount, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ExpenseAccountClient : System.ServiceModel.ClientBase<eGastosWS.ExpenseAccountServiceReference.IExpenseAccount>, eGastosWS.ExpenseAccountServiceReference.IExpenseAccount {
        
        public ExpenseAccountClient() {
        }
        
        public ExpenseAccountClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExpenseAccountClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpenseAccountClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExpenseAccountClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void initiateVariables(
                    System.DateTime requestDate, 
                    string companyName, 
                    int companyCode, 
                    int CeCoCode, 
                    int CeCoMiniCode, 
                    string CeCoMiniName, 
                    bool isMiniEvent, 
                    string arrival, 
                    string departureDate, 
                    string returnDate, 
                    string PEPElementId, 
                    string PEPElementName, 
                    string currencyId, 
                    string currencyName, 
                    string initiatorLogin, 
                    string initiatorName, 
                    string responsibleLogin, 
                    string responsibleName, 
                    string responsibleEmployeeNum, 
                    string responsibleUserName, 
                    bool pasteur, 
                    int areaId, 
                    string areaText, 
                    bool salesForce, 
                    string nationalManagerLogin, 
                    string nationalManagerName, 
                    bool debitCard, 
                    bool strike, 
                    bool isCFDI) {
            base.Channel.initiateVariables(requestDate, companyName, companyCode, CeCoCode, CeCoMiniCode, CeCoMiniName, isMiniEvent, arrival, departureDate, returnDate, PEPElementId, PEPElementName, currencyId, currencyName, initiatorLogin, initiatorName, responsibleLogin, responsibleName, responsibleEmployeeNum, responsibleUserName, pasteur, areaId, areaText, salesForce, nationalManagerLogin, nationalManagerName, debitCard, strike, isCFDI);
        }
        
        public void createExpenseAccountDetail(
                    int idExpenseAccountDetail, 
                    System.DateTime expenseDate, 
                    int idAccount, 
                    string accountName, 
                    double amount, 
                    string invoiceNumber, 
                    string place, 
                    int numberOfDiners, 
                    double IVA, 
                    bool healthProfessional, 
                    bool hasPAClient, 
                    double total, 
                    int observationId, 
                    string observationName, 
                    int idXml, 
                    double amountCFDI, 
                    double ivaCFDI, 
                    int idExtract, 
                    double amountExtract, 
                    bool conciliated, 
                    bool strike) {
            base.Channel.createExpenseAccountDetail(idExpenseAccountDetail, expenseDate, idAccount, accountName, amount, invoiceNumber, place, numberOfDiners, IVA, healthProfessional, hasPAClient, total, observationId, observationName, idXml, amountCFDI, ivaCFDI, idExtract, amountExtract, conciliated, strike);
        }
        
        public void createPAClient(int idExpenseAccountDetail, string code, string name) {
            base.Channel.createPAClient(idExpenseAccountDetail, code, name);
        }
        
        public void createResponsible(string responsibleMail, double gasLimit) {
            base.Channel.createResponsible(responsibleMail, gasLimit);
        }
        
        public string validateAndSaveRequest(int attachCount) {
            return base.Channel.validateAndSaveRequest(attachCount);
        }
        
        public bool updateRequest(int ultimusNumber) {
            return base.Channel.updateRequest(ultimusNumber);
        }
        
        public eGastosWS.ExpenseAccountServiceReference.UltExpenseFlowVariables getUltExpenseFlowVariables() {
            return base.Channel.getUltExpenseFlowVariables();
        }
        
        public eGastosWS.ExpenseAccountServiceReference.UltRequest getUltRequest() {
            return base.Channel.getUltRequest();
        }
        
        public eGastosWS.ExpenseAccountServiceReference.UltExpenseAccount getUltExpenseAccount() {
            return base.Channel.getUltExpenseAccount();
        }
        
        public eGastosWS.ExpenseAccountServiceReference.UltExpenseAccountDetail[] getUltExpenseAccountDetailList() {
            return base.Channel.getUltExpenseAccountDetailList();
        }
        
        public eGastosWS.ExpenseAccountServiceReference.UltPAClient[] getUltPAClientList() {
            return base.Channel.getUltPAClientList();
        }
    }
}
