//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:2.0.50727.5477
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eGastosWS.MissionOrderServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UltExpenseFlowVariables", Namespace="http://schemas.datacontract.org/2004/07/Entities.Ultimus")]
    [System.SerializableAttribute()]
    public partial class UltExpenseFlowVariables : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeDirAreaGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeDirFinanzasGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeDirGralGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool activeManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionAutorizador1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionAutorizador2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionAutorizador3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionAutorizador4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionController1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionController2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionControllingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionDirAreaGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionFinanzasGastosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionNationalManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionObservadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string jobFunctionResponsibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string summaryTextField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activeDirAreaGastos {
            get {
                return this.activeDirAreaGastosField;
            }
            set {
                if ((this.activeDirAreaGastosField.Equals(value) != true)) {
                    this.activeDirAreaGastosField = value;
                    this.RaisePropertyChanged("activeDirAreaGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activeDirFinanzasGastos {
            get {
                return this.activeDirFinanzasGastosField;
            }
            set {
                if ((this.activeDirFinanzasGastosField.Equals(value) != true)) {
                    this.activeDirFinanzasGastosField = value;
                    this.RaisePropertyChanged("activeDirFinanzasGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activeDirGralGastos {
            get {
                return this.activeDirGralGastosField;
            }
            set {
                if ((this.activeDirGralGastosField.Equals(value) != true)) {
                    this.activeDirGralGastosField = value;
                    this.RaisePropertyChanged("activeDirGralGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool activeManager {
            get {
                return this.activeManagerField;
            }
            set {
                if ((this.activeManagerField.Equals(value) != true)) {
                    this.activeManagerField = value;
                    this.RaisePropertyChanged("activeManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionAutorizador1 {
            get {
                return this.jobFunctionAutorizador1Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionAutorizador1Field, value) != true)) {
                    this.jobFunctionAutorizador1Field = value;
                    this.RaisePropertyChanged("jobFunctionAutorizador1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionAutorizador2 {
            get {
                return this.jobFunctionAutorizador2Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionAutorizador2Field, value) != true)) {
                    this.jobFunctionAutorizador2Field = value;
                    this.RaisePropertyChanged("jobFunctionAutorizador2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionAutorizador3 {
            get {
                return this.jobFunctionAutorizador3Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionAutorizador3Field, value) != true)) {
                    this.jobFunctionAutorizador3Field = value;
                    this.RaisePropertyChanged("jobFunctionAutorizador3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionAutorizador4 {
            get {
                return this.jobFunctionAutorizador4Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionAutorizador4Field, value) != true)) {
                    this.jobFunctionAutorizador4Field = value;
                    this.RaisePropertyChanged("jobFunctionAutorizador4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionController1 {
            get {
                return this.jobFunctionController1Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionController1Field, value) != true)) {
                    this.jobFunctionController1Field = value;
                    this.RaisePropertyChanged("jobFunctionController1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionController2 {
            get {
                return this.jobFunctionController2Field;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionController2Field, value) != true)) {
                    this.jobFunctionController2Field = value;
                    this.RaisePropertyChanged("jobFunctionController2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionControlling {
            get {
                return this.jobFunctionControllingField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionControllingField, value) != true)) {
                    this.jobFunctionControllingField = value;
                    this.RaisePropertyChanged("jobFunctionControlling");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionDirAreaGastos {
            get {
                return this.jobFunctionDirAreaGastosField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionDirAreaGastosField, value) != true)) {
                    this.jobFunctionDirAreaGastosField = value;
                    this.RaisePropertyChanged("jobFunctionDirAreaGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionFinanzasGastos {
            get {
                return this.jobFunctionFinanzasGastosField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionFinanzasGastosField, value) != true)) {
                    this.jobFunctionFinanzasGastosField = value;
                    this.RaisePropertyChanged("jobFunctionFinanzasGastos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionNationalManager {
            get {
                return this.jobFunctionNationalManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionNationalManagerField, value) != true)) {
                    this.jobFunctionNationalManagerField = value;
                    this.RaisePropertyChanged("jobFunctionNationalManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionObservador {
            get {
                return this.jobFunctionObservadorField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionObservadorField, value) != true)) {
                    this.jobFunctionObservadorField = value;
                    this.RaisePropertyChanged("jobFunctionObservador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string jobFunctionResponsible {
            get {
                return this.jobFunctionResponsibleField;
            }
            set {
                if ((object.ReferenceEquals(this.jobFunctionResponsibleField, value) != true)) {
                    this.jobFunctionResponsibleField = value;
                    this.RaisePropertyChanged("jobFunctionResponsible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string summaryText {
            get {
                return this.summaryTextField;
            }
            set {
                if ((object.ReferenceEquals(this.summaryTextField, value) != true)) {
                    this.summaryTextField = value;
                    this.RaisePropertyChanged("summaryText");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UltRequest", Namespace="http://schemas.datacontract.org/2004/07/Entities.Ultimus")]
    [System.SerializableAttribute()]
    public partial class UltRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CeCoCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CeCoMiniCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CeCoMiniNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CeCoNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAClientNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PEPElementIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PEPElementNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int areaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string areaTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string arrivalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int companyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string companyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currencyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double exchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string initiatorLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string initiatorNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isMiniEventField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool pasteurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime requestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsibleEmployeeNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsibleLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsibleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsiblePayMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string responsibleUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> salesForceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ultimusNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CeCoCode {
            get {
                return this.CeCoCodeField;
            }
            set {
                if ((this.CeCoCodeField.Equals(value) != true)) {
                    this.CeCoCodeField = value;
                    this.RaisePropertyChanged("CeCoCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CeCoMiniCode {
            get {
                return this.CeCoMiniCodeField;
            }
            set {
                if ((this.CeCoMiniCodeField.Equals(value) != true)) {
                    this.CeCoMiniCodeField = value;
                    this.RaisePropertyChanged("CeCoMiniCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CeCoMiniName {
            get {
                return this.CeCoMiniNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CeCoMiniNameField, value) != true)) {
                    this.CeCoMiniNameField = value;
                    this.RaisePropertyChanged("CeCoMiniName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CeCoName {
            get {
                return this.CeCoNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CeCoNameField, value) != true)) {
                    this.CeCoNameField = value;
                    this.RaisePropertyChanged("CeCoName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAClientId {
            get {
                return this.PAClientIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PAClientIdField, value) != true)) {
                    this.PAClientIdField = value;
                    this.RaisePropertyChanged("PAClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAClientName {
            get {
                return this.PAClientNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PAClientNameField, value) != true)) {
                    this.PAClientNameField = value;
                    this.RaisePropertyChanged("PAClientName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PEPElementId {
            get {
                return this.PEPElementIdField;
            }
            set {
                if ((object.ReferenceEquals(this.PEPElementIdField, value) != true)) {
                    this.PEPElementIdField = value;
                    this.RaisePropertyChanged("PEPElementId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PEPElementName {
            get {
                return this.PEPElementNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PEPElementNameField, value) != true)) {
                    this.PEPElementNameField = value;
                    this.RaisePropertyChanged("PEPElementName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int areaId {
            get {
                return this.areaIdField;
            }
            set {
                if ((this.areaIdField.Equals(value) != true)) {
                    this.areaIdField = value;
                    this.RaisePropertyChanged("areaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string areaText {
            get {
                return this.areaTextField;
            }
            set {
                if ((object.ReferenceEquals(this.areaTextField, value) != true)) {
                    this.areaTextField = value;
                    this.RaisePropertyChanged("areaText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string arrival {
            get {
                return this.arrivalField;
            }
            set {
                if ((object.ReferenceEquals(this.arrivalField, value) != true)) {
                    this.arrivalField = value;
                    this.RaisePropertyChanged("arrival");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int companyCode {
            get {
                return this.companyCodeField;
            }
            set {
                if ((this.companyCodeField.Equals(value) != true)) {
                    this.companyCodeField = value;
                    this.RaisePropertyChanged("companyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string companyName {
            get {
                return this.companyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.companyNameField, value) != true)) {
                    this.companyNameField = value;
                    this.RaisePropertyChanged("companyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currencyId {
            get {
                return this.currencyIdField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyIdField, value) != true)) {
                    this.currencyIdField = value;
                    this.RaisePropertyChanged("currencyId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currencyName {
            get {
                return this.currencyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.currencyNameField, value) != true)) {
                    this.currencyNameField = value;
                    this.RaisePropertyChanged("currencyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureDate {
            get {
                return this.departureDateField;
            }
            set {
                if ((object.ReferenceEquals(this.departureDateField, value) != true)) {
                    this.departureDateField = value;
                    this.RaisePropertyChanged("departureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double exchangeRate {
            get {
                return this.exchangeRateField;
            }
            set {
                if ((this.exchangeRateField.Equals(value) != true)) {
                    this.exchangeRateField = value;
                    this.RaisePropertyChanged("exchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idRequest {
            get {
                return this.idRequestField;
            }
            set {
                if ((this.idRequestField.Equals(value) != true)) {
                    this.idRequestField = value;
                    this.RaisePropertyChanged("idRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string initiatorLogin {
            get {
                return this.initiatorLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.initiatorLoginField, value) != true)) {
                    this.initiatorLoginField = value;
                    this.RaisePropertyChanged("initiatorLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string initiatorName {
            get {
                return this.initiatorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.initiatorNameField, value) != true)) {
                    this.initiatorNameField = value;
                    this.RaisePropertyChanged("initiatorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isMiniEvent {
            get {
                return this.isMiniEventField;
            }
            set {
                if ((this.isMiniEventField.Equals(value) != true)) {
                    this.isMiniEventField = value;
                    this.RaisePropertyChanged("isMiniEvent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool pasteur {
            get {
                return this.pasteurField;
            }
            set {
                if ((this.pasteurField.Equals(value) != true)) {
                    this.pasteurField = value;
                    this.RaisePropertyChanged("pasteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime requestDate {
            get {
                return this.requestDateField;
            }
            set {
                if ((this.requestDateField.Equals(value) != true)) {
                    this.requestDateField = value;
                    this.RaisePropertyChanged("requestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsibleEmployeeNum {
            get {
                return this.responsibleEmployeeNumField;
            }
            set {
                if ((object.ReferenceEquals(this.responsibleEmployeeNumField, value) != true)) {
                    this.responsibleEmployeeNumField = value;
                    this.RaisePropertyChanged("responsibleEmployeeNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsibleLogin {
            get {
                return this.responsibleLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.responsibleLoginField, value) != true)) {
                    this.responsibleLoginField = value;
                    this.RaisePropertyChanged("responsibleLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsibleName {
            get {
                return this.responsibleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.responsibleNameField, value) != true)) {
                    this.responsibleNameField = value;
                    this.RaisePropertyChanged("responsibleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsiblePayMethod {
            get {
                return this.responsiblePayMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.responsiblePayMethodField, value) != true)) {
                    this.responsiblePayMethodField = value;
                    this.RaisePropertyChanged("responsiblePayMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string responsibleUserName {
            get {
                return this.responsibleUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.responsibleUserNameField, value) != true)) {
                    this.responsibleUserNameField = value;
                    this.RaisePropertyChanged("responsibleUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string returnDate {
            get {
                return this.returnDateField;
            }
            set {
                if ((object.ReferenceEquals(this.returnDateField, value) != true)) {
                    this.returnDateField = value;
                    this.RaisePropertyChanged("returnDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> salesForce {
            get {
                return this.salesForceField;
            }
            set {
                if ((this.salesForceField.Equals(value) != true)) {
                    this.salesForceField = value;
                    this.RaisePropertyChanged("salesForce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string statusName {
            get {
                return this.statusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.statusNameField, value) != true)) {
                    this.statusNameField = value;
                    this.RaisePropertyChanged("statusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string typeName {
            get {
                return this.typeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.typeNameField, value) != true)) {
                    this.typeNameField = value;
                    this.RaisePropertyChanged("typeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ultimusNumber {
            get {
                return this.ultimusNumberField;
            }
            set {
                if ((this.ultimusNumberField.Equals(value) != true)) {
                    this.ultimusNumberField = value;
                    this.RaisePropertyChanged("ultimusNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UltMissionOrder", Namespace="http://schemas.datacontract.org/2004/07/Entities.Ultimus")]
    [System.SerializableAttribute()]
    public partial class UltMissionOrder : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool advanceApplyk__BackingFieldField;
        
        private double advancek__BackingFieldField;
        
        private string commentk__BackingFieldField;
        
        private int countAgencyWaitk__BackingFieldField;
        
        private bool hotelk__BackingFieldField;
        
        private int idAgencyLogk__BackingFieldField;
        
        private int idAgencyResponsek__BackingFieldField;
        
        private int idMissionOrderk__BackingFieldField;
        
        private int idRequestk__BackingFieldField;
        
        private bool itineraryk__BackingFieldField;
        
        private double nationalCurrencyk__BackingFieldField;
        
        private string objectivek__BackingFieldField;
        
        private int statusAgencyProcessk__BackingFieldField;
        
        private int statusAgencySendk__BackingFieldField;
        
        private string travelIdk__BackingFieldField;
        
        private string travelNamek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<advanceApply>k__BackingField", IsRequired=true)]
        public bool advanceApplyk__BackingField {
            get {
                return this.advanceApplyk__BackingFieldField;
            }
            set {
                if ((this.advanceApplyk__BackingFieldField.Equals(value) != true)) {
                    this.advanceApplyk__BackingFieldField = value;
                    this.RaisePropertyChanged("advanceApplyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<advance>k__BackingField", IsRequired=true)]
        public double advancek__BackingField {
            get {
                return this.advancek__BackingFieldField;
            }
            set {
                if ((this.advancek__BackingFieldField.Equals(value) != true)) {
                    this.advancek__BackingFieldField = value;
                    this.RaisePropertyChanged("advancek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<comment>k__BackingField", IsRequired=true)]
        public string commentk__BackingField {
            get {
                return this.commentk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.commentk__BackingFieldField, value) != true)) {
                    this.commentk__BackingFieldField = value;
                    this.RaisePropertyChanged("commentk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<countAgencyWait>k__BackingField", IsRequired=true)]
        public int countAgencyWaitk__BackingField {
            get {
                return this.countAgencyWaitk__BackingFieldField;
            }
            set {
                if ((this.countAgencyWaitk__BackingFieldField.Equals(value) != true)) {
                    this.countAgencyWaitk__BackingFieldField = value;
                    this.RaisePropertyChanged("countAgencyWaitk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<hotel>k__BackingField", IsRequired=true)]
        public bool hotelk__BackingField {
            get {
                return this.hotelk__BackingFieldField;
            }
            set {
                if ((this.hotelk__BackingFieldField.Equals(value) != true)) {
                    this.hotelk__BackingFieldField = value;
                    this.RaisePropertyChanged("hotelk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<idAgencyLog>k__BackingField", IsRequired=true)]
        public int idAgencyLogk__BackingField {
            get {
                return this.idAgencyLogk__BackingFieldField;
            }
            set {
                if ((this.idAgencyLogk__BackingFieldField.Equals(value) != true)) {
                    this.idAgencyLogk__BackingFieldField = value;
                    this.RaisePropertyChanged("idAgencyLogk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<idAgencyResponse>k__BackingField", IsRequired=true)]
        public int idAgencyResponsek__BackingField {
            get {
                return this.idAgencyResponsek__BackingFieldField;
            }
            set {
                if ((this.idAgencyResponsek__BackingFieldField.Equals(value) != true)) {
                    this.idAgencyResponsek__BackingFieldField = value;
                    this.RaisePropertyChanged("idAgencyResponsek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<idMissionOrder>k__BackingField", IsRequired=true)]
        public int idMissionOrderk__BackingField {
            get {
                return this.idMissionOrderk__BackingFieldField;
            }
            set {
                if ((this.idMissionOrderk__BackingFieldField.Equals(value) != true)) {
                    this.idMissionOrderk__BackingFieldField = value;
                    this.RaisePropertyChanged("idMissionOrderk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<idRequest>k__BackingField", IsRequired=true)]
        public int idRequestk__BackingField {
            get {
                return this.idRequestk__BackingFieldField;
            }
            set {
                if ((this.idRequestk__BackingFieldField.Equals(value) != true)) {
                    this.idRequestk__BackingFieldField = value;
                    this.RaisePropertyChanged("idRequestk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<itinerary>k__BackingField", IsRequired=true)]
        public bool itineraryk__BackingField {
            get {
                return this.itineraryk__BackingFieldField;
            }
            set {
                if ((this.itineraryk__BackingFieldField.Equals(value) != true)) {
                    this.itineraryk__BackingFieldField = value;
                    this.RaisePropertyChanged("itineraryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<nationalCurrency>k__BackingField", IsRequired=true)]
        public double nationalCurrencyk__BackingField {
            get {
                return this.nationalCurrencyk__BackingFieldField;
            }
            set {
                if ((this.nationalCurrencyk__BackingFieldField.Equals(value) != true)) {
                    this.nationalCurrencyk__BackingFieldField = value;
                    this.RaisePropertyChanged("nationalCurrencyk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<objective>k__BackingField", IsRequired=true)]
        public string objectivek__BackingField {
            get {
                return this.objectivek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.objectivek__BackingFieldField, value) != true)) {
                    this.objectivek__BackingFieldField = value;
                    this.RaisePropertyChanged("objectivek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<statusAgencyProcess>k__BackingField", IsRequired=true)]
        public int statusAgencyProcessk__BackingField {
            get {
                return this.statusAgencyProcessk__BackingFieldField;
            }
            set {
                if ((this.statusAgencyProcessk__BackingFieldField.Equals(value) != true)) {
                    this.statusAgencyProcessk__BackingFieldField = value;
                    this.RaisePropertyChanged("statusAgencyProcessk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<statusAgencySend>k__BackingField", IsRequired=true)]
        public int statusAgencySendk__BackingField {
            get {
                return this.statusAgencySendk__BackingFieldField;
            }
            set {
                if ((this.statusAgencySendk__BackingFieldField.Equals(value) != true)) {
                    this.statusAgencySendk__BackingFieldField = value;
                    this.RaisePropertyChanged("statusAgencySendk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<travelId>k__BackingField", IsRequired=true)]
        public string travelIdk__BackingField {
            get {
                return this.travelIdk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.travelIdk__BackingFieldField, value) != true)) {
                    this.travelIdk__BackingFieldField = value;
                    this.RaisePropertyChanged("travelIdk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<travelName>k__BackingField", IsRequired=true)]
        public string travelNamek__BackingField {
            get {
                return this.travelNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.travelNamek__BackingFieldField, value) != true)) {
                    this.travelNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("travelNamek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UltItinerary", Namespace="http://schemas.datacontract.org/2004/07/Entities.Ultimus")]
    [System.SerializableAttribute()]
    public partial class UltItinerary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string arrivalCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string arrivalCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> arrivalDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> departureDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string departureHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idConsecutiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idItineraryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idLedgerAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idMissionOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameLedgerAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameTravelTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string observationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string returnHourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int travelTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string arrivalCity {
            get {
                return this.arrivalCityField;
            }
            set {
                if ((object.ReferenceEquals(this.arrivalCityField, value) != true)) {
                    this.arrivalCityField = value;
                    this.RaisePropertyChanged("arrivalCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string arrivalCountry {
            get {
                return this.arrivalCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.arrivalCountryField, value) != true)) {
                    this.arrivalCountryField = value;
                    this.RaisePropertyChanged("arrivalCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> arrivalDate {
            get {
                return this.arrivalDateField;
            }
            set {
                if ((this.arrivalDateField.Equals(value) != true)) {
                    this.arrivalDateField = value;
                    this.RaisePropertyChanged("arrivalDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureCity {
            get {
                return this.departureCityField;
            }
            set {
                if ((object.ReferenceEquals(this.departureCityField, value) != true)) {
                    this.departureCityField = value;
                    this.RaisePropertyChanged("departureCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureCountry {
            get {
                return this.departureCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.departureCountryField, value) != true)) {
                    this.departureCountryField = value;
                    this.RaisePropertyChanged("departureCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> departureDate {
            get {
                return this.departureDateField;
            }
            set {
                if ((this.departureDateField.Equals(value) != true)) {
                    this.departureDateField = value;
                    this.RaisePropertyChanged("departureDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departureHour {
            get {
                return this.departureHourField;
            }
            set {
                if ((object.ReferenceEquals(this.departureHourField, value) != true)) {
                    this.departureHourField = value;
                    this.RaisePropertyChanged("departureHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idConsecutive {
            get {
                return this.idConsecutiveField;
            }
            set {
                if ((this.idConsecutiveField.Equals(value) != true)) {
                    this.idConsecutiveField = value;
                    this.RaisePropertyChanged("idConsecutive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idItinerary {
            get {
                return this.idItineraryField;
            }
            set {
                if ((this.idItineraryField.Equals(value) != true)) {
                    this.idItineraryField = value;
                    this.RaisePropertyChanged("idItinerary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idLedgerAccount {
            get {
                return this.idLedgerAccountField;
            }
            set {
                if ((this.idLedgerAccountField.Equals(value) != true)) {
                    this.idLedgerAccountField = value;
                    this.RaisePropertyChanged("idLedgerAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idMissionOrder {
            get {
                return this.idMissionOrderField;
            }
            set {
                if ((this.idMissionOrderField.Equals(value) != true)) {
                    this.idMissionOrderField = value;
                    this.RaisePropertyChanged("idMissionOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameLedgerAccount {
            get {
                return this.nameLedgerAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.nameLedgerAccountField, value) != true)) {
                    this.nameLedgerAccountField = value;
                    this.RaisePropertyChanged("nameLedgerAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nameTravelType {
            get {
                return this.nameTravelTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.nameTravelTypeField, value) != true)) {
                    this.nameTravelTypeField = value;
                    this.RaisePropertyChanged("nameTravelType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string observations {
            get {
                return this.observationsField;
            }
            set {
                if ((object.ReferenceEquals(this.observationsField, value) != true)) {
                    this.observationsField = value;
                    this.RaisePropertyChanged("observations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string returnHour {
            get {
                return this.returnHourField;
            }
            set {
                if ((object.ReferenceEquals(this.returnHourField, value) != true)) {
                    this.returnHourField = value;
                    this.RaisePropertyChanged("returnHour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int travelType {
            get {
                return this.travelTypeField;
            }
            set {
                if ((this.travelTypeField.Equals(value) != true)) {
                    this.travelTypeField = value;
                    this.RaisePropertyChanged("travelType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UltHotel", Namespace="http://schemas.datacontract.org/2004/07/Entities.Ultimus")]
    [System.SerializableAttribute()]
    public partial class UltHotel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double IVAk__BackingFieldField;
        
        private string addressk__BackingFieldField;
        
        private System.DateTime checkInDatek__BackingFieldField;
        
        private System.DateTime checkoutDatek__BackingFieldField;
        
        private string cityk__BackingFieldField;
        
        private string countryk__BackingFieldField;
        
        private string hotelNamek__BackingFieldField;
        
        private double hotelTaxk__BackingFieldField;
        
        private int idConsecutivek__BackingFieldField;
        
        private int idHotelk__BackingFieldField;
        
        private int idLegerAccountk__BackingFieldField;
        
        private int idMissionOrderk__BackingFieldField;
        
        private int idRatedk__BackingFieldField;
        
        private string lineStatusNamek__BackingFieldField;
        
        private int lineStatusk__BackingFieldField;
        
        private string nameLegerAccountk__BackingFieldField;
        
        private string observationsk__BackingFieldField;
        
        private double otherTaxesk__BackingFieldField;
        
        private double quotedRatek__BackingFieldField;
        
        private double realRatek__BackingFieldField;
        
        private string reservationk__BackingFieldField;
        
        private bool statusk__BackingFieldField;
        
        private string telephonek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IVA>k__BackingField", IsRequired=true)]
        public double IVAk__BackingField {
            get {
                return this.IVAk__BackingFieldField;
            }
            set {
                if ((this.IVAk__BackingFieldField.Equals(value) != true)) {
                    this.IVAk__BackingFieldField = value;
                    this.RaisePropertyChanged("IVAk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<address>k__BackingField", IsRequired=true)]
        public string addressk__BackingField {
            get {
                return this.addressk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.addressk__BackingFieldField, value) != true)) {
                    this.addressk__BackingFieldField = value;
                    this.RaisePropertyChanged("addressk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<checkInDate>k__BackingField", IsRequired=true)]
        public System.DateTime checkInDatek__BackingField {
            get {
                return this.checkInDatek__BackingFieldField;
            }
            set {
                if ((this.checkInDatek__BackingFieldField.Equals(value) != true)) {
                    this.checkInDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("checkInDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<checkoutDate>k__BackingField", IsRequired=true)]
        public System.DateTime checkoutDatek__BackingField {
            get {
                return this.checkoutDatek__BackingFieldField;
            }
            set {
                if ((this.checkoutDatek__BackingFieldField.Equals(value) != true)) {
                    this.checkoutDatek__BackingFieldField = value;
                    this.RaisePropertyChanged("checkoutDatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<city>k__BackingField", IsRequired=true)]
        public string cityk__BackingField {
            get {
                return this.cityk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.cityk__BackingFieldField, value) != true)) {
                    this.cityk__BackingFieldField = value;
                    this.RaisePropertyChanged("cityk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<country>k__BackingField", IsRequired=true)]
        public string countryk__BackingField {
            get {
                return this.countryk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.countryk__BackingFieldField, value) != true)) {
                    this.countryk__BackingFieldField = value;
                    this.RaisePropertyChanged("countryk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<hotelName>k__BackingField", IsRequired=true)]
        public string hotelNamek__BackingField {
            get {
                return this.hotelNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.hotelNamek__BackingFieldField, value) != true)) {
                    this.hotelNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("hotelNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<hotelTax>k__BackingField", IsRequired=true)]
        public double hotelTaxk__BackingField {
            get {
                return this.hotelTaxk__BackingFieldField;
            }
            set {
                if ((this.hotelTaxk__BackingFieldField.Equals(value) != true)) {
                    this.hotelTaxk__BackingFieldField = value;
                    this.RaisePropertyChanged("hotelTaxk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<idConsecutive>k__BackingField", IsRequired=true)]
        public int idConsecutivek__BackingField {
            get {
                return this.idConsecutivek__BackingFieldField;
            }
            set {
                if ((this.idConsecutivek__BackingFieldField.Equals(value) != true)) {
                    this.idConsecutivek__BackingFieldField = value;
                    this.RaisePropertyChanged("idConsecutivek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<idHotel>k__BackingField", IsRequired=true)]
        public int idHotelk__BackingField {
            get {
                return this.idHotelk__BackingFieldField;
            }
            set {
                if ((this.idHotelk__BackingFieldField.Equals(value) != true)) {
                    this.idHotelk__BackingFieldField = value;
                    this.RaisePropertyChanged("idHotelk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<idLegerAccount>k__BackingField", IsRequired=true)]
        public int idLegerAccountk__BackingField {
            get {
                return this.idLegerAccountk__BackingFieldField;
            }
            set {
                if ((this.idLegerAccountk__BackingFieldField.Equals(value) != true)) {
                    this.idLegerAccountk__BackingFieldField = value;
                    this.RaisePropertyChanged("idLegerAccountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<idMissionOrder>k__BackingField", IsRequired=true)]
        public int idMissionOrderk__BackingField {
            get {
                return this.idMissionOrderk__BackingFieldField;
            }
            set {
                if ((this.idMissionOrderk__BackingFieldField.Equals(value) != true)) {
                    this.idMissionOrderk__BackingFieldField = value;
                    this.RaisePropertyChanged("idMissionOrderk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<idRated>k__BackingField", IsRequired=true)]
        public int idRatedk__BackingField {
            get {
                return this.idRatedk__BackingFieldField;
            }
            set {
                if ((this.idRatedk__BackingFieldField.Equals(value) != true)) {
                    this.idRatedk__BackingFieldField = value;
                    this.RaisePropertyChanged("idRatedk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<lineStatusName>k__BackingField", IsRequired=true)]
        public string lineStatusNamek__BackingField {
            get {
                return this.lineStatusNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.lineStatusNamek__BackingFieldField, value) != true)) {
                    this.lineStatusNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("lineStatusNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<lineStatus>k__BackingField", IsRequired=true)]
        public int lineStatusk__BackingField {
            get {
                return this.lineStatusk__BackingFieldField;
            }
            set {
                if ((this.lineStatusk__BackingFieldField.Equals(value) != true)) {
                    this.lineStatusk__BackingFieldField = value;
                    this.RaisePropertyChanged("lineStatusk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<nameLegerAccount>k__BackingField", IsRequired=true)]
        public string nameLegerAccountk__BackingField {
            get {
                return this.nameLegerAccountk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.nameLegerAccountk__BackingFieldField, value) != true)) {
                    this.nameLegerAccountk__BackingFieldField = value;
                    this.RaisePropertyChanged("nameLegerAccountk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<observations>k__BackingField", IsRequired=true)]
        public string observationsk__BackingField {
            get {
                return this.observationsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.observationsk__BackingFieldField, value) != true)) {
                    this.observationsk__BackingFieldField = value;
                    this.RaisePropertyChanged("observationsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<otherTaxes>k__BackingField", IsRequired=true)]
        public double otherTaxesk__BackingField {
            get {
                return this.otherTaxesk__BackingFieldField;
            }
            set {
                if ((this.otherTaxesk__BackingFieldField.Equals(value) != true)) {
                    this.otherTaxesk__BackingFieldField = value;
                    this.RaisePropertyChanged("otherTaxesk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<quotedRate>k__BackingField", IsRequired=true)]
        public double quotedRatek__BackingField {
            get {
                return this.quotedRatek__BackingFieldField;
            }
            set {
                if ((this.quotedRatek__BackingFieldField.Equals(value) != true)) {
                    this.quotedRatek__BackingFieldField = value;
                    this.RaisePropertyChanged("quotedRatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<realRate>k__BackingField", IsRequired=true)]
        public double realRatek__BackingField {
            get {
                return this.realRatek__BackingFieldField;
            }
            set {
                if ((this.realRatek__BackingFieldField.Equals(value) != true)) {
                    this.realRatek__BackingFieldField = value;
                    this.RaisePropertyChanged("realRatek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<reservation>k__BackingField", IsRequired=true)]
        public string reservationk__BackingField {
            get {
                return this.reservationk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.reservationk__BackingFieldField, value) != true)) {
                    this.reservationk__BackingFieldField = value;
                    this.RaisePropertyChanged("reservationk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<status>k__BackingField", IsRequired=true)]
        public bool statusk__BackingField {
            get {
                return this.statusk__BackingFieldField;
            }
            set {
                if ((this.statusk__BackingFieldField.Equals(value) != true)) {
                    this.statusk__BackingFieldField = value;
                    this.RaisePropertyChanged("statusk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<telephone>k__BackingField", IsRequired=true)]
        public string telephonek__BackingField {
            get {
                return this.telephonek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.telephonek__BackingFieldField, value) != true)) {
                    this.telephonek__BackingFieldField = value;
                    this.RaisePropertyChanged("telephonek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MissionOrderServiceReference.IMissionOrder")]
    public interface IMissionOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionOrder/initiateVariables", ReplyAction="http://tempuri.org/IMissionOrder/initiateVariablesResponse")]
        void initiateVariables(
                    System.DateTime requestDate, 
                    string companyName, 
                    int companyCode, 
                    int CeCoCode, 
                    string arrival, 
                    string departureDate, 
                    string returnDate, 
                    string PEPElementId, 
                    string PEPElementName, 
                    string currencyId, 
                    string currencyName, 
                    string initiatorLogin, 
                    string initiatorName, 
                    string responsibleLogin, 
                    string responsibleName, 
                    string responsibleEmployeeNum, 
                    string responsibleUserName, 
                    bool pasteur, 
                    int areaId, 
                    string areaText, 
                    bool salesForce, 
                    string travelId, 
                    string travelName, 
                    string objective, 
                    double advance, 
                    string comment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionOrder/createItinerary", ReplyAction="http://tempuri.org/IMissionOrder/createItineraryResponse")]
        void createItinerary(int idItinerary, int idLedgerAccount, string nameLedgerAccount, string departureHour, string returnHour, string observations, int travelType, string nameTravelType, string departureCountry, string departureCity, string arrivalCountry, string arrivalCity, System.DateTime departureDate, System.DateTime arrivalDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionOrder/createHotel", ReplyAction="http://tempuri.org/IMissionOrder/createHotelResponse")]
        void createHotel(int idHotel, int idLegerAccount, string nameLegerAccount, string country, string city, string observations, System.DateTime checkInDate, System.DateTime checkoutDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionOrder/validateAndSaveRequest", ReplyAction="http://tempuri.org/IMissionOrder/validateAndSaveRequestResponse")]
        string validateAndSaveRequest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionOrder/updateRequest", ReplyAction="http://tempuri.org/IMissionOrder/updateRequestResponse")]
        bool updateRequest(int ultimusNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionOrder/getUltExpenseFlowVariables", ReplyAction="http://tempuri.org/IMissionOrder/getUltExpenseFlowVariablesResponse")]
        eGastosWS.MissionOrderServiceReference.UltExpenseFlowVariables getUltExpenseFlowVariables();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionOrder/getUltRequest", ReplyAction="http://tempuri.org/IMissionOrder/getUltRequestResponse")]
        eGastosWS.MissionOrderServiceReference.UltRequest getUltRequest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionOrder/getUltMissionOrder", ReplyAction="http://tempuri.org/IMissionOrder/getUltMissionOrderResponse")]
        eGastosWS.MissionOrderServiceReference.UltMissionOrder getUltMissionOrder();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionOrder/getUltItineraryList", ReplyAction="http://tempuri.org/IMissionOrder/getUltItineraryListResponse")]
        eGastosWS.MissionOrderServiceReference.UltItinerary[] getUltItineraryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMissionOrder/getUltHotelList", ReplyAction="http://tempuri.org/IMissionOrder/getUltHotelListResponse")]
        eGastosWS.MissionOrderServiceReference.UltHotel[] getUltHotelList();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IMissionOrderChannel : eGastosWS.MissionOrderServiceReference.IMissionOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class MissionOrderClient : System.ServiceModel.ClientBase<eGastosWS.MissionOrderServiceReference.IMissionOrder>, eGastosWS.MissionOrderServiceReference.IMissionOrder {
        
        public MissionOrderClient() {
        }
        
        public MissionOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MissionOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MissionOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MissionOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void initiateVariables(
                    System.DateTime requestDate, 
                    string companyName, 
                    int companyCode, 
                    int CeCoCode, 
                    string arrival, 
                    string departureDate, 
                    string returnDate, 
                    string PEPElementId, 
                    string PEPElementName, 
                    string currencyId, 
                    string currencyName, 
                    string initiatorLogin, 
                    string initiatorName, 
                    string responsibleLogin, 
                    string responsibleName, 
                    string responsibleEmployeeNum, 
                    string responsibleUserName, 
                    bool pasteur, 
                    int areaId, 
                    string areaText, 
                    bool salesForce, 
                    string travelId, 
                    string travelName, 
                    string objective, 
                    double advance, 
                    string comment) {
            base.Channel.initiateVariables(requestDate, companyName, companyCode, CeCoCode, arrival, departureDate, returnDate, PEPElementId, PEPElementName, currencyId, currencyName, initiatorLogin, initiatorName, responsibleLogin, responsibleName, responsibleEmployeeNum, responsibleUserName, pasteur, areaId, areaText, salesForce, travelId, travelName, objective, advance, comment);
        }
        
        public void createItinerary(int idItinerary, int idLedgerAccount, string nameLedgerAccount, string departureHour, string returnHour, string observations, int travelType, string nameTravelType, string departureCountry, string departureCity, string arrivalCountry, string arrivalCity, System.DateTime departureDate, System.DateTime arrivalDate) {
            base.Channel.createItinerary(idItinerary, idLedgerAccount, nameLedgerAccount, departureHour, returnHour, observations, travelType, nameTravelType, departureCountry, departureCity, arrivalCountry, arrivalCity, departureDate, arrivalDate);
        }
        
        public void createHotel(int idHotel, int idLegerAccount, string nameLegerAccount, string country, string city, string observations, System.DateTime checkInDate, System.DateTime checkoutDate) {
            base.Channel.createHotel(idHotel, idLegerAccount, nameLegerAccount, country, city, observations, checkInDate, checkoutDate);
        }
        
        public string validateAndSaveRequest() {
            return base.Channel.validateAndSaveRequest();
        }
        
        public bool updateRequest(int ultimusNumber) {
            return base.Channel.updateRequest(ultimusNumber);
        }
        
        public eGastosWS.MissionOrderServiceReference.UltExpenseFlowVariables getUltExpenseFlowVariables() {
            return base.Channel.getUltExpenseFlowVariables();
        }
        
        public eGastosWS.MissionOrderServiceReference.UltRequest getUltRequest() {
            return base.Channel.getUltRequest();
        }
        
        public eGastosWS.MissionOrderServiceReference.UltMissionOrder getUltMissionOrder() {
            return base.Channel.getUltMissionOrder();
        }
        
        public eGastosWS.MissionOrderServiceReference.UltItinerary[] getUltItineraryList() {
            return base.Channel.getUltItineraryList();
        }
        
        public eGastosWS.MissionOrderServiceReference.UltHotel[] getUltHotelList() {
            return base.Channel.getUltHotelList();
        }
    }
}
